# aws:
#   access_key_id: 123
#   secret_access_key: 345

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: 81b543ce6c6e4f996ee48c21d2e0e9eb69f1de961f8c91d1842f66fd71dd116e19afe25f7ee8716be373bed39b1a9d10b6d522f0f8177ede7b9ef260419a657c
stripe:
  public_key: pk_test_51PVDHQP1pdtDllTEwz976jLzGsYMtDLdKkvhGrsUcRgFQkzvKvEhjOMbpiDoxiBXQaNDS6LwxjfZgCTXVdS8JCxt00e3XdqfRO
  secret_key: sk_test_51PVDHQP1pdtDllTEDDAOjc3VsRevmjbs5rwZzhlF5j2TUo80BEgaIDABxEbVW3nHwX7Vq6q1ppEOSsYJp1BTYH6c00l9kt53lw
